# Adds two integers.
# add:
# @param
#  - a0: The first integer.
#  - a1: The second integer.
# @ret
#  - a0: The sum of the two integers.
add:
# TODO:

# Subtracts two integers.
# sub:
# @param
#  - a0: The first integer.
#  - a1: The second integer.
# @ret
#  - a0: The result of the first integer minus the second integer.
sub:
# TODO:

# Multiplies two integers.
# mul:
# @param
#  - a0: The first integer.
#  - a1: The second integer.
# @ret
#  - a0: The product of the two integers.
mul:
# TODO:

# Divides two integers.
# div:
# @param
#  - a0: The numerator.
#  - a1: The denominator.
# @ret
#  - a0: The quotient of the division.
#  - a1: The remainder of the division.
div:
# TODO:
