# Allocates a block of memory.
# malloc:
# @param
#  - a0: The size of the block to allocate.
# @ret
#  - a0: The address of the allocated block, or 0 if the allocation failed.
malloc:
# TODO:

# Frees a block of memory.
# free:
# @param
#  - a0: The address of the block to free.
# @ret
#  - none
free:
# TODO:

# Copies a block of memory.
# memcpy:
# @param
#  - a0: The address of the destination.
#  - a1: The address of the source.
#  - a2: The number of bytes to copy.
# @ret
#  - a0: The address of the destination.
memcpy:
# TODO:

# Sets a block of memory to a specified value.
# memset:
# @param
#  - a0: The address of the block.
#  - a1: The value to set.
#  - a2: The number of bytes to set.
# @ret
#  - a0: The address of the block.
memset:
# TODO:
